# Generated by Django 2.2.dev20181230164339 on 2018-12-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_image/default.png', upload_to='post_image'),
        ),
    ]
