# Generated by Django 2.2.dev20181230164339 on 2019-01-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190101_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_image/default.png', upload_to='post_image'),
        ),
    ]
